name: deploy
on:
  push:
    branches:
      - main
      - release/*
jobs:
  my_job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.5.0
      - name: Setup Node.js environment
        uses: actions/setup-node@v3.6.0
        with:
          node-version: '18.x'
      - name: install pnpm
        run: npm install pnpm@7.5.0 -g 
      - name: install pnpm
        run: pnpm -v  
      - name: install dep
        run: pnpm install
      - name: build app
        run: npm run build
      - name: scp files to linux
        uses: appleboy/scp-action@v0.0.1
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USERNAME }}
          password: ${{ secrets.REMOTE_PASSWORLD }}
          port: ${{ secrets.REMOTE_PORT }}
          source: 'name: deploy
on:
  push:
    branches:
      - main
      - release/*
jobs:
  my_job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.5.0
      - name: Setup Node.js environment
        uses: actions/setup-node@v3.6.0
        with:
          node-version: '18.x'
      - name: install pnpm
        run: npm install pnpm@7.5.0 -g 
      - name: install pnpm
        run: pnpm -v  
      - name: install dep
        run: pnpm install
      - name: build app
        run: npm run build
      - name: scp files to linux
        uses: appleboy/scp-action@v0.0.1
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USERNAME }}
          password: ${{ secrets.REMOTE_PASSWORLD }}
          port: ${{ secrets.REMOTE_PORT }}
          source: 'dist/'
          target: ${{ secrets.REMOTE_TARGET }}
/'
          target: ${{ secrets.REMOTE_TARGET }}
